"""empty message

Revision ID: 491e1302eaf4
Revises: 
Create Date: 2024-03-20 11:44:56.010227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491e1302eaf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_principle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('company', sa.String(length=80), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('amazon_principle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amazon_principle_id'], ['amazon_principle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('story_applicibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('percent_applicable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_applicibility')
    op.drop_table('question')
    op.drop_table('story')
    op.drop_table('amazon_principle')
    # ### end Alembic commands ###
